# Redirect from the Netlify URL to the main URL
[[redirects]]
  from = "https://torontomegaempires.netlify.app"
  to = "https://torontomegaempires.com"
  status = 301
  force = true

#
# Redirect to MCA2 application
[[redirects]]
  from = "https://app.torontomegaempires.com"
  to = "https://crawdad.neocities.org/MCA2/"
  status = 301
  force = true

# Redirect to Discord Link
[[redirects]]
  from = "https://discord.torontomegaempires.com"
  to = "https://discord.gg/vU48JDyQeW"
  status = 302
  force = true

# Redirect to facebook
[[redirects]]
  from = "https://fb.torontomegaempires.com"
  to = "https://www.facebook.com/groups/2344614905731511"
  status = 302
  force = true

# Redirect to Google Group
[[redirects]]
  from = "https://google.torontomegaempires.com"
  to = "https://groups.google.com/g/torontomegaempires"
  status = 302
  force = true

# Redirect to latest game sign-up
[[redirects]]
  from = "https://signup.torontomegaempires.com"
  to = "https://discord.com/channels/1199457108257669231/1219112401287516161/1465107265509003480"
  status = 302
  force = true

# Redirect to latest megacon sign-up
#[[redirects]]
#  from = "https://megacon-signup.torontomegaempires.com"
#  to = "https://discord.com/channels/1199457108257669231/1219112401287516161/1446701216452313200"
#  status = 302
#  force = true
